# Generated by Django 3.2.8 on 2022-09-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20220928_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-pub_date']},
        ),
    ]
