# Generated by Django 3.2.8 on 2022-09-29 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0003_alter_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='read',
        ),
        migrations.AddField(
            model_name='item',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
    ]
